FROM node:20-alpine

WORKDIR /app

# Installer les dépendances globales
RUN npm install -g @nestjs/cli

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer toutes les dépendances (dev incluses)
RUN npm install

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 3000

# Mode développement avec hot-reload
CMD ["npm", "run", "start:dev"]
